 clear,clc;
 disp('---------start train-----------')
 disp('training......')
 %训练数据样本 ： 每种动作训练3个
 train_files = {  'D:/Database/run/daria_run.avi'...
                 'D:/Database/run/denis_run.avi'...
                 'D:/Database/run/eli_run.avi'...
                'D:/Database/walk/daria_walk.avi'...
                 'D:/Database/walk/denis_walk.avi'...
                 'D:/Database/walk/eli_walk.avi'...
                'D:/Database/jump/daria_jump.avi'...
                 'D:/Database/jump/denis_jump.avi'...
                 'D:/Database/jump/eli_jump.avi'...
                'D:/Database/bend/daria_bend.avi'...
                 'D:/Database/bend/denis_bend.avi'...
                 'D:/Database/bend/eli_bend.avi'...
                 };
        
% 设置hmm的初始状态转移矩阵以及混淆矩阵             
trans = [1];
emis = zeros(1, 11) + 1/11;

% 对所有训练样本进行特征提取以及训练
for i = 1 : length(train_files)
   video = read_avi_data(cell2mat(train_files(i)));
   x = tracking(video);
   [m, n] = size(x);
   for j = 1 : m
        [~, tmpEstE] = hmmtrain(x(j, :), trans, emis);
        estE(i, j, :) = tmpEstE;
   end
end
 
% 将训练得到的四维矩阵保存
% 四维矩阵结构如下
% [视频号，特征号，hmm_x, hmm_y]
 save mat estE;
 
 disp('---------train over-----------')